### ISSUE TITLE
[Request] Any chance to update this to support render graph in Unity 6?

### ISSUE THREAD

**Issue by melterx12** [Zhibade/unity-outline-effect#1]
Title.

Would greatly appreciate it!

**Comment by Zhibade** [comment]
@melterx12 
I do plan to add support for Render Graph. However, I haven't kept up with Unity 6 changes recently, so it will take me a bit of time to catch up and do the actual updates. Please bear with me.

I'll post a comment here once I update it.

**Comment by Zhibade** [comment]
@melterx12 
Sorry for the wait. 

I have updated the project to support Unity 6 & Render Graph ([b0a9bb4](https://github.com/Zhibade/unity-outline-effect/commit/b0a9bb41bf94ab891ab457b967c7284c414d7dcc)). Just as a note, the way the normal buffer works has changed a bit in the new version, so the normal based outline settings might need to be tweaked.

I will now close this issue. If you have any problems with it, please open a new issue so that I can look into it.

Thank you!

**Comment by melterx12** [comment]
thanks!
